// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXVcVXj39xgojzwZNgWGPRtnzIk7tQnQE',
    appId: '1:439191922967:web:2c35e4e6bce3e33f2def52',
    messagingSenderId: '439191922967',
    projectId: 'chat-appreview',
    authDomain: 'chat-appreview.firebaseapp.com',
    storageBucket: 'chat-appreview.appspot.com',
    measurementId: 'G-KHLFGYNEC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIr2UrF1Xd2OZF-CXGdqDDIYjgfAsBkY',
    appId: '1:439191922967:android:e678212ddf22d72b2def52',
    messagingSenderId: '439191922967',
    projectId: 'chat-appreview',
    storageBucket: 'chat-appreview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5ciuCuAjykeWolRd5OJhS--BerHp2IY',
    appId: '1:439191922967:ios:478fe1559878ce792def52',
    messagingSenderId: '439191922967',
    projectId: 'chat-appreview',
    storageBucket: 'chat-appreview.appspot.com',
    iosBundleId: 'com.example.cahtAppreview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5ciuCuAjykeWolRd5OJhS--BerHp2IY',
    appId: '1:439191922967:ios:478fe1559878ce792def52',
    messagingSenderId: '439191922967',
    projectId: 'chat-appreview',
    storageBucket: 'chat-appreview.appspot.com',
    iosBundleId: 'com.example.cahtAppreview',
  );
}
